import Head from 'next/head'
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>ToNinetyOne</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <Link href={""}> текст </Link>
            </div>
        </div>
    )
}
